# Generated by Django 4.2 on 2023-05-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bacapres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('desc', models.CharField(default=None, null=True)),
                ('keyword', models.CharField(default=None, max_length=50)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='bacapres_pics/')),
            ],
        ),
    ]
