# Generated by Django 4.2 on 2023-05-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacapres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacapres',
            name='name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
