# Generated by Django 4.2 on 2023-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacapres', '0002_alter_bacapres_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacapres',
            name='avatar',
            field=models.ImageField(upload_to='bacapres_pics/'),
        ),
    ]
