# Generated by Django 4.2 on 2023-06-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacapres', '0003_alter_bacapres_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacapres',
            name='avatar',
            field=models.ImageField(default='profile_pics/profileDefault.png', upload_to='bacapres_pics/'),
        ),
        migrations.AlterField(
            model_name='bacapres',
            name='keyword',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
