# Generated by Django 4.2 on 2023-05-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quota', models.IntegerField(default=3)),
            ],
        ),
    ]
