# Generated by Django 4.2 on 2023-05-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Super Admin')], default='MEMBER', max_length=50),
        ),
    ]
