# Generated by Django 4.2 on 2023-05-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profile_pics/profileDefault.png', upload_to='profile_pics/'),
        ),
    ]
