# Generated by Django 4.2 on 2023-06-05 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bacapres', '0004_alter_bacapres_avatar_alter_bacapres_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.TextField(default=None)),
                ('text', models.TextField(default=None)),
                ('user_name', models.CharField(default=None)),
                ('created_at', models.DateTimeField(default=None)),
                ('text_preprocessed', models.TextField(default=None)),
                ('sentiment', models.TextField(default=None)),
                ('bacapres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bacapres.bacapres')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.TextField(default=None)),
                ('text', models.TextField(default=None)),
                ('user_name', models.CharField(default=None)),
                ('created_at', models.DateTimeField(default=None)),
                ('bacapres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bacapres.bacapres')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('bacapres', models.ManyToManyField(to='bacapres.bacapres')),
                ('tweet', models.ManyToManyField(to='sentiment.tweet')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
