# Generated by Django 4.2 on 2023-06-10 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedTweet',
        ),
    ]
